# Generated by Django 4.2.10 on 2024-02-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_owner_id_alter_owner_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
    ]
